codecov:
  require_ci_to_pass: true

comment:
  layout: "reach, diff, flags"
  require_changes: false
  require_base: yes
  require_head: yes
  hide_project_coverage: false

coverage:
  precision: 2
  round: down
  range: 60..100
  status:
    project:
      default:
        target: 85%
        threshold: 1%
    patch:
      default:
        target: 85%
        threshold: 1%

ignore:
  - "examples/*"
  - "docs/*"
  - "benchmarks/*"
  - "**/tests/**"
  - "**/migrations/**"
