name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  tests:
    name: Pytest (${{ matrix.envset }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        envset: [core, server]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install project (editable)
        run: |
          pip install --upgrade pip
          if [ "${{ matrix.envset }}" = "server" ]; then
            pip install -e .[dev,security,server]
          else
            pip install -e .[dev,security]
          fi

      - name: Run tests with coverage
        env:
          PYTHONWARNINGS: ignore::DeprecationWarning:scipy.sparse.linalg
        run: |
          pytest -q --cov=./ --cov-report=xml --cov-report=term --cov-fail-under=85

      - name: Upload coverage to Codecov
        if: ${{ matrix.envset == 'server' }}
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-${{ matrix.envset }}
          path: coverage.xml
          if-no-files-found: warn
