name: Test & Validate (DEPRECATED - use ci.yml)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install core + dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          # Optional: install fast embedder / connector extras if needed later
          # pip install -e .[embedders-sentencetransformers,connectors-pinecone,connectors-chroma]

      - name: Lint (ruff)
        run: |
          ruff check .

      - name: Type check (mypy)
        run: |
          mypy . --ignore-missing-imports

      - name: Run tests (unit & fast)
        env:
          USE_MOCK: 'true'
          NORMALIZATION_LOAD_N: '0'  # disable long load test in CI
        run: |
          echo "This workflow is deprecated; prefer ci.yml" >&2
          pytest -k 'not normalization_load' -v --maxfail=1 --cov=. --cov-report=xml --cov-fail-under=85 || echo "(Non-blocking in deprecated workflow)"

      # Coverage threshold enforced in ci.yml. Kept non-fatal here for transition.

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          # token not required for public repos; add CODECOV_TOKEN secret if private
          files: coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Summary
        if: always()
        run: |
          echo 'Tests + type check completed.'